path: D:\Damaged-Car-parts-prediction-using-YOLOv8-main  # dataset root dir
train: D:\Damaged-Car-parts-prediction-using-YOLOv8-main\data\images\train  # train images (relative to 'path')
val: D:\Damaged-Car-parts-prediction-using-YOLOv8-main\data\images\train  # val images (relative to 'path')
 
  
# Classes
names:
  0: damaged door
  1: damaged window
  2: damaged headlight
  3: damaged mirror
  4: dent
  5: damaged hood
  6: damaged bumper
  7: damaged wind shield
